import { Buffer } from "node:buffer";

import { NextRequest } from "next/server";
import { beforeEach, describe, expect, test, vi } from "vitest";

type FetchCall = Parameters<typeof fetch>;

const resolveUrl = (value: FetchCall[0]): string => {
  if (typeof value === "string") {
    return value;
  }
  if (value instanceof URL) {
    return value.toString();
  }
  if (value instanceof Request) {
    return value.url;
  }
  return (value as { url?: string }).url ?? String(value);
};

describe("GET /api/inspiration", () => {
  beforeEach(() => {
    process.env.OPENWEATHERMAP_API_KEY = "test-weather-key";
    process.env.OPENAI_API_KEY = "test-openai-key";
    delete process.env.OPENAI_MODEL;
    delete process.env.OPENAI_MODEL_FALLBACKS;
    vi.resetModules();
  });

  test("returns an inspiring sentence generated by the LLM", async () => {
    const fetchMock = vi.fn<FetchCall, Awaited<ReturnType<typeof fetch>>[]>(
      async (input: Parameters<typeof fetch>[0], init?: RequestInit) => {
        const url = resolveUrl(input);

        if (url.includes("/geo/1.0/direct")) {
          return new Response(
            JSON.stringify([
              {
                name: "Edinburgh",
                country: "GB",
                lat: 55.9533,
                lon: -3.1883,
              },
            ]),
            {
              status: 200,
              headers: { "Content-Type": "application/json" },
            },
          );
        }

        if (url.includes("/data/2.5/weather")) {
          return new Response(
            JSON.stringify({
              weather: [{ description: "clear sky" }],
              main: { temp: 16.8, feels_like: 15.2, humidity: 62 },
              wind: { speed: 3.5 },
              clouds: { all: 12 },
            }),
            {
              status: 200,
              headers: { "Content-Type": "application/json" },
            },
          );
        }

        if (url.includes("openai.com/v1/chat/completions")) {
          const rawBody: string =
            typeof init?.body === "string"
              ? init.body
              : Buffer.isBuffer(init?.body)
              ? init.body.toString("utf8")
              : init?.body
              ? JSON.stringify(init.body)
              : "{}";

          const parsedBody = JSON.parse(rawBody);

          expect(parsedBody).toMatchObject({
            model: "gpt-4o-mini",
            messages: expect.any(Array),
          });
          expect(parsedBody.messages[1]?.content).toContain("Weather summary");

          return new Response(
            JSON.stringify({
              choices: [
                {
                  message: {
                    content: "Chase radiant autumn light",
                  },
                },
              ],
            }),
            {
              status: 200,
              headers: { "Content-Type": "application/json" },
            },
          );
        }

        throw new Error(`Unhandled fetch call for URL: ${url}`);
      },
    );

    vi.stubGlobal("fetch", fetchMock as unknown as typeof fetch);

    const { GET } = await import("@/app/api/inspiration/route");
    const request = new NextRequest("http://localhost/api/inspiration");

    const response = await GET(request);
    expect(response.status).toBe(200);

    const payload = (await response.json()) as {
      sentence: string;
      metadata: { model: string | null };
    };

    expect(payload.sentence).toBe("Chase radiant autumn light");
    expect(payload.metadata.model).toBe("gpt-4o-mini");

    expect(fetchMock).toHaveBeenCalledTimes(3);
    const openAiCall = fetchMock.mock.calls.find(([input]) =>
      resolveUrl(input).includes("openai.com"),
    );
    expect(openAiCall).toBeDefined();
  });
});
